CELL_SIZE = 10
CELL_MARGIN = 2
CELL_COLOR = "black"

CELL_NUM_WIDTH, CELL_NUM_HEIGHT = 50, 25


BG_COLOR = "light gray"
GRID_COLOR = "black"
WIDTH, HEIGHT = 1000, 600
W, H = WIDTH // CELL_SIZE, HEIGHT // CELL_SIZE
FPS = 10
